### ISSUE TITLE
_mm_set_epi8 could be replaced with _mm_set_epi64x

### ISSUE THREAD

**Issue by planet36** [dragontamer/AESRand#1]
This is only a suggestion, not an issue.

`_mm_set_epi8(0x2f, 0x2b, 0x29, 0x25, 0x1f, 0x1d, 0x17, 0x13, 0x11, 0x0D, 0x0B, 0x07, 0x05, 0x03, 0x02, 0x01);`
could be replaced with
`_mm_set_epi64x(0x2f2b29251f1d1713, 0x110d0b0705030201);`

**Comment by lemire** [comment]
Sure... but that should be strictly equivalent. No?

**Comment by planet36** [comment]
Yes, the result is the same, but the code is more succinct.

```
const __m128i a = _mm_set_epi8(0x2f, 0x2b, 0x29, 0x25, 0x1f, 0x1d, 0x17, 0x13, 0x11, 0x0d, 0x0b, 0x07, 0x05, 0x03, 0x02, 0x01);
const __m128i b = _mm_set_epi64x(0x2f2b29251f1d1713, 0x110d0b0705030201);
assert(memcmp(&a, &b, sizeof(a)) == 0);
```
